spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingnan_all?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: search
  elasticsearch:
    rest:
      uris:
        - http://192.168.68.129:9200
  thymeleaf:
    cache: false
logging:
  level:
    root: info
  file:
    path: d:/temp/jingnan
